language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - curl
      - python-dev
      - libffi-dev
      - libtool
      - automake
install:
  - "curl -L -o libgit2-0.22.3.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.3.tar.gz"
  - "tar xzf libgit2-0.22.3.tar.gz"
  - "pushd ."
  - "cd libgit2-0.22.3"
  - "mkdir build"
  - "cd build"
  - "cmake .. -DBUILD_CLAR=NO -DCMAKE_BUILD_TYPE=Release"
  - "make install"
  - "ldconfig"
  - "popd"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install ."
# command to run tests
script: py.test
sudo: false