language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - curl
      - python-dev
      - libffi-dev
      - libtool
      - automake
env:
  global:
    - LIBGIT2=$HOME/libgit2
    - LD_LIBRARY_PATH=$LIBGIT2/lib
before_install:
  - bash local_libgit2.sh
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install ."
# command to run tests
script: py.test
sudo: false