language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get update"
  - "sudo apt-get install -y cmake build-essential curl python-dev libffi-dev libtool automake python-pip"
  - "curl -L -o libgit2-0.22.3.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.3.tar.gz"
  - "tar xzf libgit2-0.22.3.tar.gz"
  - "cd libgit2-0.22.3"
  - "mkdir build"
  - "cd build"
  - "cmake .. -DBUILD_CLAR=NO -DCMAKE_BUILD_TYPE=Release"
  - "sudo make install"
  - "sudo ldconfig"
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install ."
# command to run tests
script: py.test